# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 17:26
# from __future__ import unicode_literals
#
# from django.db import migrations, models
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('lists', '0006_auto_20161229_1726'),
#     ]
#
#     operations = [
#         migrations.AlterField(
#             model_name='item',
#             name='text',
#             field=models.TextField(default=''),
#         ),
#     ]
# 0007_auto_20161229_1726
